#!/usr/bin/env python
# coding : utf-8


"""
Pentagon Numbers

Pentagonal numbers are generated by the formula, Pn = n(3n -1)/2. The first ten pentagonal numbers are:
1,5, 12, 22, 35, 51, 70, 92, 117, 145, . ..
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pi and Pk for which their sum and difference are pentagonal and D = |Pk - Pjl is
minimised; what is the value of D?

"""

PID = 44
ASNSER = 5482660

def pentagonal(num) -> int:

    pen = (num * (3 * num - 1))/2

    return pen


def is_pentagonal(sum) -> bool:

    n = 1 + (1+24*sum) ** 0.5
    
    return n % 6 == 0

def solve() -> int:
    j = 2
    while True:
        pj = pentagonal(j)
        k = 1

        while k < j:
            pk = pentagonal(k)
            h = pj + pk
            c = pj - pk
            if is_pentagonal(h) and is_pentagonal(c):
                return int(c)
            k += 1
        j += 1


    
