#!/usr/bin/env python
# coding: utf-8


"""
Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2,, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""


PID = 2
ANSWER = 4613732

def solve() -> int:
    a = 1
    b = 2
    c = a + b
    sum = 0
    while c < 4000000:
        a = b
        b = c
        c = a + b 
        print(c, end=' ')

        if c % 2 == 0:
            sum = sum + c

    return sum+2

